#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           InstaL,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           Left,          tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           Right,         tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port5,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RaiseR,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RaiseL,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           Lift1_R,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Lift1_L,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          InstaR,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define abs(X) ((X < 0) ? -1 * X : X)
task main()
{
motor[Lift1_L]= 127;
	motor[Lift1_R]= 127;
	wait(0.5);
	motor[Lift1_L]= 0;
	motor[Lift1_R]= 0;
// The lift moves up 0.5 second

	motor[InstaL]= 100;
	motor[InstaR]= 100;
	wait(1);
//Mobile goal goes forward

	motor[InstaL]= 0;
	motor[InstaR]= 0;
//Mobile goal stops


	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	//while(abs(getMotorEncoder(Left)) < 627)
	while(abs(getMotorEncoder(Right)) < 627) {
		motor[Left]= 127;
		motor[Right]= 127;
	}
	motor[Left]= 0;
	motor[Right]= 0;
//Robot goes forward

	motor[Lift1_L]= -100;
	motor[Lift1_R]= -100;
	wait(0.25);
//The lift moves down 0.25 seconds
 	motor[Lift1_L]= 0;
	motor[Lift1_R]= 0;
//The lift stops

	motor[Claw]= 127;
	wait(0.5);
//Opens claw

	motor[Lift1_L]= 100;
	motor[Lift1_R]= 100;
	wait(1);
//The lift moves up 1 second
 	motor[Lift1_L]= 0;
	motor[Lift1_R]= 0;
//The lift stops

	motor[InstaL]= -100;
	motor[InstaR]= -100;
	wait(1);
//Mobile goal goes backward

	motor[InstaL&&InstaR]=0;
//Mobile goal stops

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	while(abs(getMotorEncoder(Right)) < 627)
	{
		motor[Left]= -127;
		motor[Right]= -127;
	}

	motor[Left]= 0;
	motor[Right]= 0;
// Robot goes backwards

	motor[Claw]= 0;
//Claw stops



}
